// <auto-generated />
using System;
using Membr.Module.Member.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Membr.Module.Member.Persistence.Migrations
{
    [DbContext(typeof(MembersDbContext))]
    [Migration("20260830075105_add_udf_fields")]
    partial class add_udf_fields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("members")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Membr.Module.Member.Domain.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.ToTable("members", "members");
                });

            modelBuilder.Entity("Membr.Module.Member.Domain.MemberUdfValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("UdfDefinitionId")
                        .HasColumnType("integer")
                        .HasColumnName("udf_definition_id");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_member_udf_values");

                    b.HasIndex("UdfDefinitionId")
                        .HasDatabaseName("ix_member_udf_values_udf_definition_id");

                    b.HasIndex("MemberId", "UdfDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_member_udf_values_member_id_udf_definition_id");

                    b.ToTable("member_udf_values", "members");
                });

            modelBuilder.Entity("Membr.Module.Member.Domain.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("MembershipTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("membership_type_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_memberships");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_memberships_member_id");

                    b.HasIndex("MembershipTypeId")
                        .HasDatabaseName("ix_memberships_membership_type_id");

                    b.ToTable("memberships", "members");
                });

            modelBuilder.Entity("Membr.Module.Member.Domain.MembershipRenewal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MembershipId")
                        .HasColumnType("integer")
                        .HasColumnName("membership_id");

                    b.Property<DateTime>("NewEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_end_date");

                    b.Property<DateTime>("PreviousEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_end_date");

                    b.Property<DateTime>("RenewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("renewed_at");

                    b.HasKey("Id")
                        .HasName("pk_membership_renewals");

                    b.HasIndex("MembershipId")
                        .HasDatabaseName("ix_membership_renewals_membership_id");

                    b.ToTable("membership_renewals", "members");
                });

            modelBuilder.Entity("Membr.Module.Member.Domain.MembershipSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowMultipleMemberships")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_multiple_memberships");

                    b.HasKey("Id")
                        .HasName("pk_membership_settings");

                    b.ToTable("membership_settings", "members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowMultipleMemberships = false
                        });
                });

            modelBuilder.Entity("Membr.Module.Member.Domain.MembershipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMonths")
                        .HasColumnType("integer")
                        .HasColumnName("duration_months");

                    b.Property<int?>("FixedTermAnchorDay")
                        .HasColumnType("integer")
                        .HasColumnName("fixed_term_anchor_day");

                    b.Property<int?>("FixedTermAnchorMonth")
                        .HasColumnType("integer")
                        .HasColumnName("fixed_term_anchor_month");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RenewalMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("renewal_mode");

                    b.HasKey("Id")
                        .HasName("pk_membership_types");

                    b.ToTable("membership_types", "members");
                });

            modelBuilder.Entity("Membr.Module.Member.Domain.UdfDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("default_value");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("options");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_udf_definitions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_udf_definitions_name");

                    b.ToTable("udf_definitions", "members");
                });

            modelBuilder.Entity("Membr.Module.Member.Domain.MemberUdfValue", b =>
                {
                    b.HasOne("Membr.Module.Member.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_udf_values_members_member_id");

                    b.HasOne("Membr.Module.Member.Domain.UdfDefinition", "UdfDefinition")
                        .WithMany()
                        .HasForeignKey("UdfDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_udf_values_udf_definitions_udf_definition_id");

                    b.Navigation("Member");

                    b.Navigation("UdfDefinition");
                });

            modelBuilder.Entity("Membr.Module.Member.Domain.Membership", b =>
                {
                    b.HasOne("Membr.Module.Member.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_members_member_id");

                    b.HasOne("Membr.Module.Member.Domain.MembershipType", "MembershipType")
                        .WithMany()
                        .HasForeignKey("MembershipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_membership_types_membership_type_id");

                    b.Navigation("Member");

                    b.Navigation("MembershipType");
                });

            modelBuilder.Entity("Membr.Module.Member.Domain.MembershipRenewal", b =>
                {
                    b.HasOne("Membr.Module.Member.Domain.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membership_renewals_memberships_membership_id");

                    b.Navigation("Membership");
                });
#pragma warning restore 612, 618
        }
    }
}
