/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members */
        get: operations["ListMembers"];
        put?: never;
        /** Create a new member */
        post: operations["CreateMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search members */
        get: operations["SearchMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve member */
        get: operations["GetMember"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/{memberId}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a member's memberships */
        get: operations["ListMemberMemberships"];
        put?: never;
        /** Grant a member a new membership */
        post: operations["CreateMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/{memberId}/memberships/{membershipId}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renew an existing membership */
        post: operations["RenewMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/membershiptypes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List membership types */
        get: operations["ListMembershipTypes"];
        put?: never;
        /** Create a new membership type */
        post: operations["CreateMembershipType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/membershiptypes/{Id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve membership type */
        get: operations["GetMembershipType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings/membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve global membership settings */
        get: operations["GetMembershipSettings"];
        /** Update global membership settings */
        put: operations["UpdateMembershipSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve dashboard statistics */
        get: operations["GetDashboardStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/udffields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user-defined field definitions */
        get: operations["ListUdfDefinitions"];
        put?: never;
        /** Create a user-defined field definition */
        post: operations["CreateUdfDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/udffields/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every member's user-defined field values */
        get: operations["ListAllMemberUdfValues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/udffields/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a user-defined field definition */
        get: operations["GetUdfDefinition"];
        /** Update a user-defined field definition */
        put: operations["UpdateUdfDefinition"];
        post?: never;
        /** Delete a user-defined field definition */
        delete: operations["DeleteUdfDefinition"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/udffields/{id}/apply-default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply a field's default value to every member */
        post: operations["ApplyUdfDefaultToAllMembers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/{memberId}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a member's contact details */
        get: operations["ListMemberContacts"];
        put?: never;
        /** Add a contact detail for a member */
        post: operations["CreateMemberContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/{memberId}/contacts/{contactId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a member's contact detail */
        put: operations["UpdateMemberContact"];
        post?: never;
        /** Delete a member's contact detail */
        delete: operations["DeleteMemberContact"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/{memberId}/udf-values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a member's user-defined field values */
        get: operations["ListMemberUdfValues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/{memberId}/udf-values/{definitionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a member's value for a user-defined field */
        put: operations["UpdateMemberUdfValue"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/{memberId}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a member's tokens */
        get: operations["ListMemberTokens"];
        put?: never;
        /** Assign a new token to a member */
        post: operations["CreateMemberToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/{memberId}/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a member's token */
        delete: operations["RevokeMemberToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tokens/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Look up the member owning a token (used by the in-app scan tool) */
        get: operations["LookupToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/members/by-token/{value}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve a scanned token to its member and membership information */
        get: operations["LookupMemberByToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a refresh token for a new access token */
        post: operations["Refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current refresh token */
        post: operations["Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current authenticated user */
        get: operations["Me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List admin users */
        get: operations["ListUsers"];
        put?: never;
        /** Create a new admin user */
        post: operations["CreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available roles */
        get: operations["ListRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessTokenResponse: {
            accessToken: string;
        };
        ContactDto: {
            /** Format: int32 */
            id: number | string;
            contactType: components["schemas"]["ContactType"];
            contactDetail: string;
            isPrimary: boolean;
        };
        /** @enum {unknown} */
        ContactType: "Email" | "Phone";
        CreateMemberContactInput: {
            contactType: components["schemas"]["ContactType"];
            contactDetail: string;
            isPrimary: boolean;
        };
        CreateMemberContactRequest: {
            contactType: components["schemas"]["ContactType"];
            contactDetail: string;
            isPrimary: boolean;
        };
        CreateMemberRequest: {
            firstName: string;
            surname: string;
            /** Format: date */
            dateOfBirth: string;
            contacts: null | components["schemas"]["CreateMemberContactInput"][];
        };
        CreateMembershipRequest: {
            /** Format: int32 */
            membershipTypeId: number | string;
        };
        CreateMembershipTypeRequest: {
            name: string;
            description: null | string;
            isActive: boolean;
            renewalMode: components["schemas"]["MembershipRenewalMode"];
            /** Format: int32 */
            durationMonths: null | number | string;
            /** Format: int32 */
            fixedTermAnchorMonth: null | number | string;
            /** Format: int32 */
            fixedTermAnchorDay: null | number | string;
        };
        CreateMemberTokenRequest: {
            tokenType: components["schemas"]["TokenType"];
            value: string;
        };
        CreateUdfDefinitionRequest: {
            name: string;
            type: components["schemas"]["UdfFieldType"];
            options: null | string[];
            defaultValue: null | string;
        };
        CreateUserRequest: {
            email: string;
            displayName: string;
            password: string;
            role: string;
        };
        DashboardStatsDto: {
            /** Format: int32 */
            totalMembers: number | string;
            /** Format: int32 */
            activeMembers: number | string;
            membershipTypeBreakdown: components["schemas"]["MembershipTypeBreakdownDto"][];
            monthlyActivity: components["schemas"]["MonthlyActivityDto"][];
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        MemberDto: {
            /** Format: int32 */
            id: number | string;
            firstName: string;
            surname: string;
            /** Format: date */
            dateOfBirth: string;
        };
        MembershipDto: {
            /** Format: int32 */
            id: number | string;
            /** Format: int32 */
            memberId: number | string;
            /** Format: int32 */
            membershipTypeId: number | string;
            membershipTypeName: string;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
            isActive: boolean;
        };
        /** @enum {unknown} */
        MembershipRenewalMode: "Rolling" | "FixedTerm";
        MembershipSettingsDto: {
            allowMultipleMemberships: boolean;
        };
        MembershipTypeBreakdownDto: {
            /** Format: int32 */
            membershipTypeId: number | string;
            membershipTypeName: string;
            /** Format: int32 */
            activeCount: number | string;
        };
        MembershipTypeDto: {
            /** Format: int32 */
            id: number | string;
            name: string;
            description: null | string;
            isActive: boolean;
            renewalMode: components["schemas"]["MembershipRenewalMode"];
            /** Format: int32 */
            durationMonths: null | number | string;
            /** Format: int32 */
            fixedTermAnchorMonth: null | number | string;
            /** Format: int32 */
            fixedTermAnchorDay: null | number | string;
        };
        MemberSummaryDto: {
            /** Format: int32 */
            id: number | string;
            firstName: string;
            surname: string;
        };
        MemberUdfFieldDto: {
            /** Format: int32 */
            definitionId: number | string;
            name: string;
            type: components["schemas"]["UdfFieldType"];
            options: string[];
            value: null | string;
        };
        MemberUdfValueDto: {
            /** Format: int32 */
            memberId: number | string;
            /** Format: int32 */
            udfDefinitionId: number | string;
            value: null | string;
        };
        MeResponse: {
            id: string;
            email: string;
            displayName: string;
            roles: string[];
        };
        MonthlyActivityDto: {
            /** Format: int32 */
            year: number | string;
            /** Format: int32 */
            month: number | string;
            /** Format: int32 */
            newMemberships: number | string;
            /** Format: int32 */
            renewals: number | string;
        };
        PagedResultOfMemberDto: {
            items: components["schemas"]["MemberDto"][];
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        TokenDto: {
            /** Format: int32 */
            id: number | string;
            /** Format: int32 */
            memberId: number | string;
            tokenType: components["schemas"]["TokenType"];
            value: string;
            isRevoked: boolean;
            /** Format: date-time */
            revokedAt: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        TokenLookupDto: {
            /** Format: int32 */
            memberId: number | string;
            firstName: string;
            surname: string;
            memberships: components["schemas"]["TokenLookupMembershipDto"][];
        };
        TokenLookupMembershipDto: {
            membershipTypeName: string;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
            isActive: boolean;
        };
        /** @enum {unknown} */
        TokenType: "Rfid" | "Qr" | "Barcode" | "Number";
        UdfDefinitionDto: {
            /** Format: int32 */
            id: number | string;
            name: string;
            type: components["schemas"]["UdfFieldType"];
            isActive: boolean;
            options: string[];
            defaultValue: null | string;
        };
        /** @enum {unknown} */
        UdfFieldType: "DateTime" | "Date" | "Bool" | "String" | "MultiSelect";
        UdfValuesGridDto: {
            definitions: components["schemas"]["UdfDefinitionDto"][];
            members: components["schemas"]["MemberSummaryDto"][];
            values: components["schemas"]["MemberUdfValueDto"][];
        };
        UpdateMemberContactRequest: {
            contactType: components["schemas"]["ContactType"];
            contactDetail: string;
            isPrimary: boolean;
        };
        UpdateMembershipSettingsRequest: {
            allowMultipleMemberships: boolean;
        };
        UpdateMemberUdfValueBody: {
            value: null | string;
        };
        UpdateUdfDefinitionRequest: {
            name: string;
            options: null | string[];
            defaultValue: null | string;
            isActive: boolean;
        };
        UserDto: {
            id: string;
            email: string;
            displayName: string;
            roles: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListMembers: {
        parameters: {
            query?: {
                page?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfMemberDto"];
                };
            };
        };
    };
    CreateMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    SearchMembers: {
        parameters: {
            query: {
                q: string;
                page?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfMemberDto"];
                };
            };
        };
    };
    GetMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListMemberMemberships: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipDto"][];
                };
            };
        };
    };
    CreateMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number | string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMembershipRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RenewMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number | string;
                membershipId: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListMembershipTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipTypeDto"][];
                };
            };
        };
    };
    CreateMembershipType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMembershipTypeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipTypeDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetMembershipType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                Id: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipTypeDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMembershipSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipSettingsDto"];
                };
            };
        };
    };
    UpdateMembershipSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMembershipSettingsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipSettingsDto"];
                };
            };
        };
    };
    GetDashboardStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStatsDto"];
                };
            };
        };
    };
    ListUdfDefinitions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UdfDefinitionDto"][];
                };
            };
        };
    };
    CreateUdfDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUdfDefinitionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UdfDefinitionDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ListAllMemberUdfValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UdfValuesGridDto"];
                };
            };
        };
    };
    GetUdfDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UdfDefinitionDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateUdfDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number | string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUdfDefinitionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UdfDefinitionDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteUdfDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplyUdfDefaultToAllMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UdfDefinitionDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListMemberContacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactDto"][];
                };
            };
        };
    };
    CreateMemberContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number | string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberContactRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateMemberContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number | string;
                contactId: number | string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberContactRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteMemberContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number | string;
                contactId: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListMemberUdfValues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberUdfFieldDto"][];
                };
            };
        };
    };
    UpdateMemberUdfValue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number | string;
                definitionId: number | string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberUdfValueBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberUdfValueDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListMemberTokens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenDto"][];
                };
            };
        };
    };
    CreateMemberToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number | string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberTokenRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RevokeMemberToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number | string;
                tokenId: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LookupToken: {
        parameters: {
            query: {
                value: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenLookupDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LookupMemberByToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                value: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenLookupDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
        };
    };
    Refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
        };
    };
    Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    ListUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"][];
                };
            };
        };
    };
    CreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ListRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
}
